-- friendly_title + friendly_description dos 87 CNAEs atendidos (ME).
-- Gerado por _sistema/gerar-friendly-cnae.py. Idempotente: pode rodar de novo.

UPDATE cnae SET friendly_title = 'Aluguel de videogames e jogos eletrônicos', friendly_description = 'Aluguel de consoles, videogames, fliperamas e brinquedos eletrônicos. Você aluga o aparelho; explorar o jogo no seu ponto é outra atividade.' WHERE code = '7729201';
UPDATE cnae SET friendly_title = 'Aluguel de móveis, eletrodomésticos e instrumentos', friendly_description = 'Aluguel de móveis, cadeiras, eletrodomésticos, ar-condicionado e instrumentos musicais para uso doméstico ou pessoal.' WHERE code = '7729202';
UPDATE cnae SET friendly_title = 'Aluguel de material médico', friendly_description = 'Aluguel de cadeira de rodas, cama hospitalar, muletas, inaladores e material médico em geral.' WHERE code = '7729203';
UPDATE cnae SET friendly_title = 'Albergue e hostel', friendly_description = 'Hospedagem em albergue ou hostel, com cama por noite ou quarto compartilhado. Não cobre albergue assistencial, que é serviço social.' WHERE code = '5590601';
UPDATE cnae SET friendly_title = 'Pensão e casa de cômodos', friendly_description = 'Hospedagem em pensão, com ou sem refeição incluída.' WHERE code = '5590603';
UPDATE cnae SET friendly_title = 'Edição de livros', friendly_description = 'Edição de livros impressos e digitais, e-books, audiolivros, apostilas, dicionários e atlas.' WHERE code = '5811500';
UPDATE cnae SET friendly_title = 'Edição de jornal diário', friendly_description = 'Edição de jornal que sai todo dia, impresso, eletrônico ou na internet.' WHERE code = '5812301';
UPDATE cnae SET friendly_title = 'Edição de jornal semanal ou mensal', friendly_description = 'Edição de jornal que não sai todo dia: semanal, quinzenal ou mensal, impresso ou na internet.' WHERE code = '5812302';
UPDATE cnae SET friendly_title = 'Edição de revistas', friendly_description = 'Edição de revistas e publicações periódicas, impressas, eletrônicas ou na internet.' WHERE code = '5813100';
UPDATE cnae SET friendly_title = 'Web design', friendly_description = 'Criação e desenvolvimento de sites, portais e páginas na internet.' WHERE code = '6201502';
UPDATE cnae SET friendly_title = 'Edição de catálogos, listas e guias', friendly_description = 'Edição de catálogos, listas, guias, calendários, cartões-postais e cartões de felicitação.' WHERE code = '5819100';
UPDATE cnae SET friendly_title = 'Produção de vídeo publicitário', friendly_description = 'Produção de comercial de TV, filme institucional e vídeo para campanha publicitária.' WHERE code = '5911102';
UPDATE cnae SET friendly_title = 'Dublagem', friendly_description = 'Dublagem de filmes, séries, programas de televisão e vídeos.' WHERE code = '5912001';
UPDATE cnae SET friendly_title = 'Mixagem e edição de som', friendly_description = 'Mixagem sonora para filme, vídeo e programa de televisão.' WHERE code = '5912002';
UPDATE cnae SET friendly_title = 'Pesquisa em ciências sociais e humanas', friendly_description = 'Pesquisa e desenvolvimento em direito, economia, linguística, arqueologia, artes e áreas afins.' WHERE code = '7220700';
UPDATE cnae SET friendly_title = 'Estúdio de gravação e edição musical', friendly_description = 'Gravação de som, edição de música e gestão de direitos autorais de obras musicais.' WHERE code = '5920100';
UPDATE cnae SET friendly_title = 'Desenvolvimento de software sob encomenda', friendly_description = 'Criação de sistema, aplicativo ou banco de dados feito sob medida para um cliente específico.' WHERE code = '6201501';
UPDATE cnae SET friendly_title = 'Desenvolvimento de software customizável', friendly_description = 'Desenvolvimento e licenciamento de software que você adapta para cada cliente.' WHERE code = '6202300';
UPDATE cnae SET friendly_title = 'Desenvolvimento de software pronto', friendly_description = 'Desenvolvimento e licenciamento de software vendido igual para todo mundo, sem adaptação por cliente.' WHERE code = '6203100';
UPDATE cnae SET friendly_title = 'Consultoria em TI', friendly_description = 'Consultoria, assessoria e auditoria em sistemas, software e infraestrutura de informática.' WHERE code = '6204000';
UPDATE cnae SET friendly_title = 'Suporte técnico em TI', friendly_description = 'Help-desk, instalação, configuração e manutenção de sistemas e equipamentos de informática.' WHERE code = '6209100';
UPDATE cnae SET friendly_title = 'Hospedagem de sites e tratamento de dados', friendly_description = 'Hospedagem na internet, gestão de banco de dados de terceiros e processamento de dados.' WHERE code = '6311900';
UPDATE cnae SET friendly_title = 'Agência de notícias', friendly_description = 'Apuração, produção e distribuição de material noticioso para veículos de imprensa.' WHERE code = '6391700';
UPDATE cnae SET friendly_title = 'Locadora de filmes e mídias', friendly_description = 'Aluguel de DVD, Blu-ray, CD e cartuchos de videogame.' WHERE code = '7722500';
UPDATE cnae SET friendly_title = 'Aluguel de roupas, joias e acessórios', friendly_description = 'Aluguel de roupa, traje de festa, enxoval de noiva, calçado, joia e acessório.' WHERE code = '7723300';
UPDATE cnae SET friendly_title = 'Pesquisa em ciências exatas e naturais', friendly_description = 'Pesquisa e desenvolvimento em agronomia, biologia, biomedicina, física, química e áreas afins.' WHERE code = '7210000';
UPDATE cnae SET friendly_title = 'Agência de publicidade', friendly_description = 'Criação de campanha publicitária, propaganda e material de anúncio para clientes.' WHERE code = '7311400';
UPDATE cnae SET friendly_title = 'Venda de espaço publicitário', friendly_description = 'Aluguel e revenda de espaço físico para publicidade: outdoor, busdoor, cartaz e painel. Não cobre espaço em rádio, TV e jornal.' WHERE code = '7312200';
UPDATE cnae SET friendly_title = 'Promoção de vendas', friendly_description = 'Demonstração de produto em ponto de venda, panfletagem e distribuição de material promocional.' WHERE code = '7319002';
UPDATE cnae SET friendly_title = 'Marketing direto', friendly_description = 'Marketing e publicidade por mala direta, telefone e canais diretos com o cliente.' WHERE code = '7319003';
UPDATE cnae SET friendly_title = 'Consultoria em publicidade', friendly_description = 'Consultoria e assessoria em marketing, branding e gestão de marca.' WHERE code = '7319004';
UPDATE cnae SET friendly_title = 'Pesquisa de mercado e de opinião', friendly_description = 'Levantamento e análise de dados de mercado e de opinião pública, incluindo a análise estatística.' WHERE code = '7320300';
UPDATE cnae SET friendly_title = 'Design de interiores', friendly_description = 'Projeto e decoração de ambientes, além de vitrine e organização visual de loja.' WHERE code = '7410202';
UPDATE cnae SET friendly_title = 'Design de produto', friendly_description = 'Desenho industrial e criação de produto, roupa, joia e maquete.' WHERE code = '7410203';
UPDATE cnae SET friendly_title = 'Design gráfico e outros designs', friendly_description = 'Criação de logotipo, identidade visual, arte gráfica digital e design de jogos, sem a programação.' WHERE code = '7410299';
UPDATE cnae SET friendly_title = 'Fotografia', friendly_description = 'Fotografia em estúdio, de evento, de imprensa e por conta própria. Não cobre foto aérea nem submarina.' WHERE code = '7420001';
UPDATE cnae SET friendly_title = 'Laboratório e revelação fotográfica', friendly_description = 'Revelação de fotos, montagem de slides e edição de imagem fotográfica.' WHERE code = '7420003';
UPDATE cnae SET friendly_title = 'Filmagem de festas e eventos', friendly_description = 'Gravação e produção de vídeo de festa, casamento e evento cultural.' WHERE code = '7420004';
UPDATE cnae SET friendly_title = 'Microfilmagem e digitalização de acervo', friendly_description = 'Microfilmagem de documentos e acervos.' WHERE code = '7420005';
UPDATE cnae SET friendly_title = 'Tradução e interpretação', friendly_description = 'Tradução de textos, interpretação, revisão gramatical e copywriting.' WHERE code = '7490101';
UPDATE cnae SET friendly_title = 'Intermediação de negócios e representação', friendly_description = 'Aproximar quem compra e quem vende: intermediação de contratos, serviços e negócios em geral. Não cobre negócio imobiliário.' WHERE code = '7490104';
UPDATE cnae SET friendly_title = 'Agenciamento de atletas e artistas', friendly_description = 'Empresariamento de atleta, ator, modelo e artista para atividade esportiva, cultural ou artística.' WHERE code = '7490105';
UPDATE cnae SET friendly_title = 'Aluguel de equipamento esportivo e de lazer', friendly_description = 'Aluguel de bicicleta, barco de lazer, pula-pula, tobogã e brinquedo não eletrônico, sem operar o equipamento.' WHERE code = '7721700';
UPDATE cnae SET friendly_title = 'Aluguel de outros objetos pessoais e domésticos', friendly_description = 'Aluguel de itens que não cabem nas outras listas: livros, plantas e flores, peruca, decoração de Natal.' WHERE code = '7729299';
UPDATE cnae SET friendly_title = 'Aluguel de equipamento de escritório', friendly_description = 'Aluguel de computador, celular, data-show, caixa registradora e máquina de escritório.' WHERE code = '7733100';
UPDATE cnae SET friendly_title = 'Aulas de esporte', friendly_description = 'Escolinha e aulas de futebol, natação, artes marciais, capoeira, atletismo e outros esportes.' WHERE code = '8591100';
UPDATE cnae SET friendly_title = 'Teleatendimento e call center', friendly_description = 'Atendimento a clientes por telefone para outras empresas: SAC, central de atendimento e call center.' WHERE code = '8220200';
UPDATE cnae SET friendly_title = 'Aulas de dança', friendly_description = 'Aulas e academia de dança: balé, dança de salão, dança popular e folclórica.' WHERE code = '8592901';
UPDATE cnae SET friendly_title = 'Serviços de escritório e apoio administrativo', friendly_description = 'Recepção, arquivo de documentos e apoio operacional combinados, para empresas e profissionais liberais.' WHERE code = '8211300';
UPDATE cnae SET friendly_title = 'Fotocópias e impressão', friendly_description = 'Xerox, cópia, digitalização e impressão de documentos.' WHERE code = '8219901';
UPDATE cnae SET friendly_title = 'Organização de eventos e festas', friendly_description = 'Organização de feira, congresso, exposição, festa infantil e festa de família, e a gestão do espaço do evento.' WHERE code = '8230001';
UPDATE cnae SET friendly_title = 'Cobrança e consulta cadastral', friendly_description = 'Cobrança de faturas e dívidas para terceiros, análise de cadastro e aprovação de crédito.' WHERE code = '8291100';
UPDATE cnae SET friendly_title = 'Envase e empacotamento para terceiros', friendly_description = 'Envasar, fracionar e empacotar produtos de outras empresas, sob contrato.' WHERE code = '8292000';
UPDATE cnae SET friendly_title = 'Gravação de carimbos', friendly_description = 'Gravação de carimbos. Não cobre a fabricação do carimbo, que é indústria.' WHERE code = '8299703';
UPDATE cnae SET friendly_title = 'Lan house e sala de internet', friendly_description = 'Sala com computadores para acesso à internet, digitação, escaneamento e apoio administrativo.' WHERE code = '8299707';
UPDATE cnae SET friendly_title = 'Curso de informática', friendly_description = 'Aulas e cursos de informática, computador e uso da internet.' WHERE code = '8599603';
UPDATE cnae SET friendly_title = 'Curso profissionalizante e de gestão', friendly_description = 'Cursos de capacitação profissional, aperfeiçoamento e treinamento gerencial, presenciais ou a distância.' WHERE code = '8599604';
UPDATE cnae SET friendly_title = 'Curso preparatório para concursos', friendly_description = 'Cursinho para concurso público, vestibular e ENEM.' WHERE code = '8599605';
UPDATE cnae SET friendly_title = 'Aulas de teatro e artes cênicas', friendly_description = 'Aulas de teatro, impostação de voz e direção de espetáculo. Não cobre dança nem curso de nível técnico ou superior.' WHERE code = '8592902';
UPDATE cnae SET friendly_title = 'Aulas de música', friendly_description = 'Aulas de música e conservatório, sem ser curso superior.' WHERE code = '8592903';
UPDATE cnae SET friendly_title = 'Aulas de arte e cultura', friendly_description = 'Aulas de artesanato, pintura, escultura e outras artes não listadas em outra atividade.' WHERE code = '8592999';
UPDATE cnae SET friendly_title = 'Aulas de idiomas', friendly_description = 'Cursos de inglês, espanhol, francês e outros idiomas, incluindo exame de proficiência.' WHERE code = '8593700';
UPDATE cnae SET friendly_title = 'Agência matrimonial', friendly_description = 'Agência de casamento e de encontros.' WHERE code = '9609202';
UPDATE cnae SET friendly_title = 'Conserto de relógios', friendly_description = 'Conserto de relógio, cronômetro e artigos de relojoaria.' WHERE code = '9529103';
UPDATE cnae SET friendly_title = 'Restauração de obras de arte', friendly_description = 'Restauração de quadro, escultura, imagem sacra e objeto de arte.' WHERE code = '9002702';
UPDATE cnae SET friendly_title = 'Produção de teatro', friendly_description = 'Companhia de teatro, ator independente e produção de espetáculo teatral.' WHERE code = '9001901';
UPDATE cnae SET friendly_title = 'Produção musical', friendly_description = 'Banda, cantor, intérprete, autoria e arranjo musical.' WHERE code = '9001902';
UPDATE cnae SET friendly_title = 'Produção de espetáculo de dança', friendly_description = 'Companhia e conjunto de dança, incluindo dança folclórica, e a produção do espetáculo.' WHERE code = '9001903';
UPDATE cnae SET friendly_title = 'Produção de circo e teatro de bonecos', friendly_description = 'Circo, espetáculo circense, fantoche e marionete.' WHERE code = '9001904';
UPDATE cnae SET friendly_title = 'Artista plástico, jornalista ou escritor', friendly_description = 'Trabalho independente de artista plástico, escritor, jornalista, cartunista, caligrafista e criador de desenho animado.' WHERE code = '9002701';
UPDATE cnae SET friendly_title = 'Restauração de prédios históricos', friendly_description = 'Conservação e restauro de prédio tombado e imóvel de valor histórico. Não cobre o projeto de arquitetura.' WHERE code = '9102302';
UPDATE cnae SET friendly_title = 'Organização de eventos esportivos', friendly_description = 'Produção e promoção de competição esportiva, além de associação e federação de esporte.' WHERE code = '9319101';
UPDATE cnae SET friendly_title = 'Salão de sinuca e bilhar', friendly_description = 'Exploração de mesa de sinuca e bilhar no seu ponto.' WHERE code = '9329803';
UPDATE cnae SET friendly_title = 'Fliperama e jogos eletrônicos', friendly_description = 'Exploração de fliperama, jogo eletrônico e cyber café com foco em jogos.' WHERE code = '9329804';
UPDATE cnae SET friendly_title = 'Conserto de computadores', friendly_description = 'Assistência técnica em computador, notebook e equipamento de informática.' WHERE code = '9511800';
UPDATE cnae SET friendly_title = 'Conserto de celulares e equipamentos de comunicação', friendly_description = 'Conserto de celular, telefone, câmera de vídeo e equipamento de comunicação.' WHERE code = '9512600';
UPDATE cnae SET friendly_title = 'Conserto de eletrodomésticos e eletrônicos', friendly_description = 'Conserto de eletrodoméstico, eletrônico de uso pessoal, antena e alarme residencial.' WHERE code = '9521500';
UPDATE cnae SET friendly_title = 'Conserto de calçados e bolsas', friendly_description = 'Sapataria: conserto e renovação de calçado, bolsa e artigo de viagem.' WHERE code = '9529101';
UPDATE cnae SET friendly_title = 'Chaveiro', friendly_description = 'Cópia de chave e conserto de fechadura e cadeado.' WHERE code = '9529102';
UPDATE cnae SET friendly_title = 'Conserto de bicicletas', friendly_description = 'Oficina de bicicleta, bicicleta elétrica, triciclo e cadeira de rodas não motorizada.' WHERE code = '9529104';
UPDATE cnae SET friendly_title = 'Conserto e restauro de móveis', friendly_description = 'Conserto de móvel, armário, tapeçaria e estofamento.' WHERE code = '9529105';
UPDATE cnae SET friendly_title = 'Conserto de joias', friendly_description = 'Conserto e gravação em joias.' WHERE code = '9529106';
UPDATE cnae SET friendly_title = 'Conserto de outros objetos pessoais e domésticos', friendly_description = 'Conserto que não cabe nas outras listas: amolar facas e cutelaria, artigos de borracha, acessórios de roupa.' WHERE code = '9529199';
UPDATE cnae SET friendly_title = 'Cabeleireiro, manicure e pedicure', friendly_description = 'Salão de beleza, barbearia, corte, alisamento, manicure, pedicure e podologia.' WHERE code = '9602501';
UPDATE cnae SET friendly_title = 'Outros serviços profissionais e técnicos', friendly_description = 'Consultoria técnica que não cabe nas outras listas: culinária, moda e imagem pessoal, projetos culturais, sommelier.' WHERE code = '7490199';
UPDATE cnae SET friendly_title = 'Preparação de documentos e apoio administrativo', friendly_description = 'Redação e conferência de texto, elaboração de crachá e cartão de visita, assessoria para visto e passaporte.' WHERE code = '8219999';
UPDATE cnae SET friendly_title = 'Portal de conteúdo e sites de informação', friendly_description = 'Portal de conteúdo na internet, gestão de redes sociais para terceiros e banco de informação para consulta.' WHERE code = '6319400';
